[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InteroperableCSV = "1fbc523b-fa59-4a4c-89bb-0e3fcf7c697f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Peddy = "0ce30ac1-e258-4977-baf6-e7a1803367e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
